// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9oG7lzOgB8R7NtSAZUyL0PAzxQHWU1-w',
    appId: '1:835311886740:web:f90ee78df3b5e8e99faf81',
    messagingSenderId: '835311886740',
    projectId: 'oilie-butt-skater-app',
    authDomain: 'oilie-butt-skater-app.firebaseapp.com',
    storageBucket: 'oilie-butt-skater-app.appspot.com',
    measurementId: 'G-VP7XP68N7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwMFu_rrMDIAieRqPt2VFYdQcLg2DvqF8',
    appId: '1:835311886740:android:acaf8ac6f39b37b99faf81',
    messagingSenderId: '835311886740',
    projectId: 'oilie-butt-skater-app',
    storageBucket: 'oilie-butt-skater-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7xs2yw7KG8WKyqXN0GgqvV4AX9VoMB_k',
    appId: '1:835311886740:ios:73545926153022f99faf81',
    messagingSenderId: '835311886740',
    projectId: 'oilie-butt-skater-app',
    storageBucket: 'oilie-butt-skater-app.appspot.com',
    iosBundleId: 'com.example.oilieButtSkaterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7xs2yw7KG8WKyqXN0GgqvV4AX9VoMB_k',
    appId: '1:835311886740:ios:73545926153022f99faf81',
    messagingSenderId: '835311886740',
    projectId: 'oilie-butt-skater-app',
    storageBucket: 'oilie-butt-skater-app.appspot.com',
    iosBundleId: 'com.example.oilieButtSkaterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9oG7lzOgB8R7NtSAZUyL0PAzxQHWU1-w',
    appId: '1:835311886740:web:ed75e09359e86c149faf81',
    messagingSenderId: '835311886740',
    projectId: 'oilie-butt-skater-app',
    authDomain: 'oilie-butt-skater-app.firebaseapp.com',
    storageBucket: 'oilie-butt-skater-app.appspot.com',
    measurementId: 'G-RZDFX0YG9C',
  );

}